# Generated by Django 4.2.2 on 2023-06-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_plantastico', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
