# Generated by Django 4.2.2 on 2023-07-01 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_plantastico', '0003_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('codigo_carrito', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_plantastico.usuario')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='ProductoCarrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField()),
                ('codigo_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_plantastico.carrito')),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_plantastico.producto')),
            ],
        ),
    ]
